### ISSUE TITLE
Flaky E2E test: namespace should be deleted error

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#686]
**Description**

Some of our E2E test pipelines are sometimes failing when the fast integration test tries to delete a namespace (e.g. https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1483046628448276480/build-log.txt). Issue happens randomly:

     Upgrade test cleanup
       1) Test namespaces should be deleted

     0 passing (2m)
     1 failing

     1) Upgrade test cleanup
          Test namespaces should be deleted:
        Error: Timeout for deleting namespaces: mocks,test
         at Timeout._onTimeout (utils/index.js:407:18)
         at listOnTimeout (internal/timers.js:557:17)
         at processTimers (internal/timers.js:500:7)

**Expected result**

Test should be able to delete the namespace without issues.

**Actual result**

Test fails to delete the namespace randomly.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
Think this is an issue we have to move to the Kyma backlog as it's not a reconciler specific issue

**Comment by tobiscr** [comment]
Fixed as part of the pipeline stabilisation initaitive.
