### ISSUE TITLE
Flaky CI/CD pipeline: pre-main-control-plane-reconciler-e2e

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#761]
**Description**

We got the feedback from @piotrmiskiewicz that the E2E pipeline `pre-main-control-plane-reconciler-e2e` (https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e) is unstable and shows a flaky behaviour.

We have to verify the pipeline and ensure the results are stable and continuously deterministic.

**Expected result**

CI pipeline delivers stable results without instability.

**Actual result**

Pipeline behaves flaky.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
Seems pipelines is now much more stable as before, but we are still facing temporarily occuring issues:

E.g. 

* https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1349/pre-main-control-plane-reconciler-e2e/1492181856035016704/build-log.txt

      Error when querying Grafana: 503 : no healthy upstream
      Checking redirect for grafana
            1) Grafana redirects should work
        22 passing (9m)
        1 failing

        1) Executing Standard Testsuite:
             Grafana Tests:
               Grafana redirects should work:

            Grafana redirect to grafana landing page does not work!      
            actual expected

* https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1349/pre-main-control-plane-reconciler-e2e/1492061109107036160/build-log.txt. (probably related to #686 )

      Checking redirect for kyma docs
            ✓ Grafana redirects should work (48598ms)

        22 passing (14m)
        1 failing

        1) Executing Standard Testsuite:
             CommerceMock Tests:
               Test namespaces should be deleted:
           Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/test.js)
            at listOnTimeout (internal/timers.js:557:17)
            at processTimers (internal/timers.js:500:7)
